LuxeAssist/LuxeAssist/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('request/',include("request.urls")),
    path('accounts/',include("accounts.urls")),
    path('service/',include("services.urls")),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LuxeAssist/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_page_view, name="register_page_view"),
    path("login/", views.login_page_view, name="login_page_view"),
    path("logout/", views.logout_page_view, name="logout_page_view"),
    path("profile/<user_id>/", views.user_profile_page_view, name="user_profile_page_view"),
    path("update/", views.update_profile_page_view, name="update_profile_page_view"),
]

LuxeAssist/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
   path("", views.home_view, name="home_view"),
   path("about/", views.about_view, name="about_view"),
   path("search/", views.search_view, name="search_view"),
   path("contact/", views.contact_view, name="contact_view"),
   path("payment/<requests_id>/", views.payment_view, name="payment_view"),
   path("not/", views.not_found_view, name="not_found_view"),
   path("display/all/contact/",views.display_all_contacts_view, name = "display_all_contacts_view"),
   path('adminn/page/',views.admin_page_view, name="admin_page_view"),
   path("success/payment/",views.success_payment_view, name="success_payment_view" )

]

LuxeAssist/services/urls.py
from django.urls import path
from . import views


app_name = "services"

urlpatterns = [
    path('add/type/', views.add_typeService_view , name="add_typeService_view"),
    path('type/details/<typeService_id>/',views.details_typeService_view, name="details_typeService_view"),
    path('update/type/<typeService_id>/',views.update_typeService_view, name="update_typeService_view"),
    path('delete/<typeService_id>/', views.delete_services_views,name="delete_services_views"),
    path('add/',views.add_service_view , name="add_service_view"),
    path('details/<service_id>/', views.details_service_view, name="details_service_view"),
    path('update/<service_id>/', views.update_service_view, name="update_service_view"),
    path('concierge/delete/<service_id>/',views.delete_servicesConcierge_views, name="delete_servicesConcierge_views"),
    path('all/services/provider/', views.all_servicesProvider_view , name="all_servicesProvider_view"),
    path('activate/user/<user_id>/',views.activate_conceirge_viwe, name = "activate_conceirge_viwe"),
    path('deactivate/user/<user_id>/',views.deactivate_conceirge_viwe, name = "deactivate_conceirge_viwe"),
    path('all/services/admin/', views.all_services_admin_view , name="all_services_admin_view"),
    path('delete/services/admin/<service_id>/', views.delete_services_admin_views , name="delete_services_admin_views"),
    path('all/service/concierge/', views.conceirge_services_view, name = "conceirge_services_view" ),
    path('all/serviceType/admin/',views.all_serviceType_admin_viwe,name="all_serviceType_admin_viwe")

]

LuxeAssist/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="image/" , default="image/default.png",blank=True)
    city = models.CharField(max_length=255 , default="Riyadh")
    address = models.CharField(max_length=255 , default="Riyadh")
    phone_number = models.CharField (max_length=255, default="0")

    GENDER_CHOICES =models.TextChoices("GENDER_CHOICES", ["Male","Female","Other"])
    
    gender = models.CharField(max_length=256, choices=GENDER_CHOICES.choices, default='')

    nationality = models.CharField(max_length=255 , default="Saudi")
    about = models.TextField()

    def __str__(self) :
        return f"{self.user.first_name} profile"

LuxeAssist/accounts/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest , HttpResponse
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate , login , logout
from .models import Profile
from django.db import IntegrityError
from services.models import Review

# Create your views here.

def register_page_view(request:HttpRequest):
    message = None

    if request.method == "POST":
        try:
            # Create a new user
            user = User.objects.create_user(username=request.POST["username"], first_name = request.POST["first_name"], last_name = request.POST["last_name"], email=request.POST["email"], password=request.POST["password"])
            user.save()

            profile = Profile(user=user, city=request.POST["city"], address=request.POST["address"], phone_number=request.POST["phone_number"])
            profile.save()

            if "user" in request.GET:
               #add to group
               group_concerge, created = Group.objects.get_or_create(name="conceirge")

               user.groups.add(group_concerge)
               user.is_active = False
               user.save()


            return redirect("accounts:login_page_view")
        except IntegrityError as e:
           message = f"Please select another username"
        except Exception as e:
          print(e)
          message = f"something went wrong {e}"


    return render(request, "accounts/register.html",{"message":message})


def login_page_view(request: HttpRequest):
    message = None

    if request.method == "POST":
        #firt : authenticate the user data
        user = authenticate(request,username = request.POST["username"], password = request.POST["password"])

        if user:
            #second: login the user
            login(request, user)
            return redirect("main:home_view")
        
        else:
           message = "Please provide correct username and password"


    return render(request, "accounts/login.html",{"message":message})


def logout_page_view(request: HttpRequest):
    
    #log out the user
    if request.user.is_authenticated:
        logout(request)    

    return redirect("accounts:login_page_view")
    

def user_profile_page_view(request: HttpRequest , user_id):
    if  not request.user.is_authenticated :
        return render(request,"main/user_not_found.html", status=401)
    try:
      user = User.objects.get(id = user_id)
      user_reviews = Review.objects.filter(user = request.user)
        
    except:
       return render(request ,"main/user_not_found.html")
        
    return render(request,"accounts/profile.html",{"user":user , "reviews":user_reviews})
    

def update_profile_page_view(request: HttpRequest):
   message = None

   if  not request.user.is_authenticated :
        return render(request,"main/user_not_found.html", status=401)

   if request.method == "POST": 
    try:
        if request.user.is_authenticated:
            user: User = request.user
            user.first_name = request.POST["first_name"]
            user.last_name = request.POST["last_name"]
            user.email=request.POST["email"]
            user.save()

            profile : Profile = request.user.profile

            if "avatar" in request.FILES:
                profile.avatar = request.FILES["avatar"]

            profile.city= request.POST["city"]
            profile.address= request.POST["address"]
            profile.phone_number= request.POST["phone_number"]
            profile.gender = request.POST["gender"]
            profile.nationality = request.POST["nationality"]
            profile.about = request.POST["about"]
            profile.save()

            return redirect("accounts:user_profile_page_view", user_id = request.user.id)
                
        else:
            return redirect("accounts:login_page_view")

    except Exception as e:
        message = f"A typing error occurred {e}"

            
   return render(request, "accounts/update.html",{"message":message})
            

LuxeAssist/accounts/templates/accounts/conserge_register.html
{% extends 'main/base.html' %}

{% block title %} Register New User {% endblock %}

{% block content %}
<div class = "wrapper pages-content">
    <section class="container content d-flex flex-column align-items-center ">
        <br>
    <h1>Concerge Register Page</h1>
    <h3>Sign Up</h3>
    {% if message %}
    <div class="alert alert-danger" role="alert">
    {{ message }}
    </div>
    {% endif %}
    <div class="d-flex flex-row gap-1 col-9">
        <div class="card-body gap-2 p-3 border border-1 rounded-2 col-12" style="background-color: #dfdddc85;">
        <div class="row">
       

        <form class="d-flex flex-column gap-1"  action="{% url 'accounts:register_page_view' %}?user=concerge" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}

            <label class="align-self-start">User Name:</label>
            <input class="form-control " type="text" name="username"  />

            <label class="align-self-start">Fisrt Name:</label>
            <input class="form-control " type="text" name="first_name"  />

            <label class="align-self-start">Last Name:</label>
            <input class="form-control " type="text" name="last_name"  />

            <label class="align-self-start">Email:</label>
            <input class="form-control" type="email" name="email" required minlength="3" />

            <label class="align-self-start">City:</label>
            <input class="form-control" type="text" name="city" />

            <label class="align-self-start">Address:</label>
            <input class="form-control" type="text" name="address" />
    

            <label class="align-self-start">Phone Number:</label>
            <input class="form-control" type="tel" name="phone_number" />

            <label class="align-self-start">Password:</label>
            <input class="form-control" type="password" name="password" required minlength="8" />


            <input class="btn btn-secondary mt-3 mb-3" type="submit" value="Sign Up" />
        </form>

    </div>

</div>
</div>
</div>
</section>
</div>
{% endblock %}

LuxeAssist/accounts/templates/accounts/login.html
{% extends 'main/base.html' %}

{% block title %} LogIn User {% endblock %}

{% block content %}
<div class = "wrapper">


    <div class="row content d-flex flex-column align-items-center ">
            <h1>Sign In </h1>
            {% if message %}
                <div class="alert alert-danger" role="alert">
                  {{ message }}
                </div>
            {% endif %}

        <div class="col-6">
           

            <form action="{% url 'accounts:login_page_view' %}" method="POST" >
                {% csrf_token %}
                <label>User Name:</label>
                <input class="form-control " type="text" name="username"  />

                <label>Password:</label>
                <input class="form-control" type="password" name="password" required minlength="8" />


                <input class="btn btn-secondary mt-3" type="submit" value="Sign In" />
                <hr>
                <h6 class = "mb-3">Don't have an account? <a href="{% url 'accounts:register_page_view' %}">Sign up</a></h6>
            </form>

        </div>

    </div>
</div>

{% endblock %}

LuxeAssist/accounts/templates/accounts/profile.html
{% extends 'main/base.html' %}

{% block title %} User profile {% endblock %}


{% block content %}
<div class = "wrapper pages-content">
    <div class="container mt-4 mb-4 p-3 d-flex justify-content-center "> 
        <div class="card p-4 "> 
            <div class="image d-flex flex-column justify-content-center align-items-center"> 
                <button class="btn btn-secondary ">
                    <img src="{{ user.profile.avatar.url }}" height="100" width="100"  class="avatar rounded-circle" />
                </button>
                <div class="d-flex flex-row justify-content-center align-items-center gap-2 ">
                <span class="name mt-3 "><h6> Name:{{ user.first_name }} {{ user.last_name }}</span></h6>
                <span class="idd"><h6>Email: <a href="mailto:{{ user.email }}">{{user.email}}</h6></a></span>
                    <span class="idd1"><h6>Address: {{user.profile.address}}</span> </h6>
                    <span class="idd1"><h6>City: {{user.profile.city}}</span> </h6>
                    <span class="idd1"><h6>Gender: {{user.profile.gender}}</span> </h6>
                    <span class="idd1"><h6>Nationality: {{user.profile.nationality}}</span> </h6>
                    
                </div>
                <div class="d-flex flex-row justify-content-center align-items-center mt-3"> 
                    <span class="number"><h6>Phone Number: <a href="tel:{{user.profile.phone_number}}">{{user.profile.phone_number}}</h6></a></span>
                </div> 
                <div class="text mt-3"> 
                    <span><h6>Nationality: {{user.profile.about}}.</span></h6> 
                </div> 
                <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"> 
                    <span><i class="fa fa-twitter"></i></span> 
                    <span><i class="fa fa-facebook-f"></i></span> 
                    <span><i class="fa fa-instagram"></i></span> 
                    <span><i class="fa fa-linkedin"></i></span>
                </div> 
            </div>
        </div>
    </div>


    <div class="container">
        <h4 style="color: rgb(99, 100, 100);">All Review </h4>
        <div class="row mt-5">
            <div class="col-4">
                {% for review in reviews %}
                <hr>
                    <h4>{{review.user.first_name}}</h4>
                    <a href="{% url 'services:details_service_view' review.services.id %}" ><h4> {{review.services.title}}</h4></a>
                    <h4>{{review.comment}}</h4>
                    <h4>{{review.rating}}</h4>
                {% endfor %}
            </div>
        </div>
    </div>
    

</div>
{% endblock %}

LuxeAssist/accounts/templates/accounts/register.html
{% extends 'main/base.html' %}

{% block title %} Register New User {% endblock %}

{% block content %}
<div class = "wrapper pages-content">
    <section class="container content d-flex flex-column align-items-center ">
        <br>
    <h1>Register Page</h1>
    <h3>Sign Up</h3>
    {% if message %}
    <div class="alert alert-danger" role="alert">
    {{ message }}
    </div>
    {% endif %}
    <div class="d-flex flex-row gap-1 col-9">
        <div class="card-body gap-2 p-3 border border-1 rounded-2 col-12" style="background-color: #dfdddc85;">
        <div class="row">

        <form class="d-flex flex-column gap-1"  action="{% if 'user' in request.GET %}{% url 'accounts:register_page_view' %}?user=coneirge{% else %}{% url 'accounts:register_page_view' %}{%endif%}" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}

            <label class="align-self-start">User Name:</label>
            <input class="form-control " type="text" name="username"  />

            <label class="align-self-start">Fisrt Name:</label>
            <input class="form-control " type="text" name="first_name"  />

            <label class="align-self-start">Last Name:</label>
            <input class="form-control " type="text" name="last_name"  />

            <label class="align-self-start">Email:</label>
            <input class="form-control" type="email" name="email" required minlength="3" />

            <label class="align-self-start">City:</label>
            <input class="form-control" type="text" name="city" />

            <label class="align-self-start">Address:</label>
            <input class="form-control" type="text" name="address" />
    

            <label class="align-self-start">Phone Number:</label>
            <input class="form-control" type="tel" name="phone_number" />

            <label class="align-self-start">Password:</label>
            <input class="form-control" type="password" name="password" required minlength="8" />


            <input class="btn btn-secondary mt-3 mb-3" type="submit" value="Sign Up" />
            <h6>Sign up as<a href="{% url 'accounts:register_page_view' %}?user=conceirge">Conserge</a></h6>
        </form>

    </div>

</div>
</div>
</div>
</section>
</div>
{% endblock %}

LuxeAssist/accounts/templates/accounts/update.html
{% extends 'main/base.html' %}

{% block title %} Update  User {% endblock %}


{% block content %}
<div class = "wrapper pages-contentt " >

<section class="container content d-flex flex-column align-items-center ">
    <br>
    <h2 style="color: aliceblue;">Update your profile</h2>
    {% if message %}
        <div class="alert alert-danger" role="alert">
        {{ message }}
        </div>
    {% endif %}
    <div class="d-flex flex-row gap-1">
        <div class="card-body gap-2 p-3 border border-1 rounded-2 " style="background-color: #dfdddc85;">
        <div class="row">
        <div class="col-12">

            <form class="d-flex flex-column gap-1" action="{% url 'accounts:update_profile_page_view' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="d-flex align-items-center gap-2 ">
                    <img src="{{ request.user.profile.avatar.url }}" width="50px" class="avatar rounded-circle"/>
                    <input class="form-control" type="file" name="avatar"  placeholder="choose avatar"/>
                </div>

                <label>Fisrt Name:</label>
                <input class="form-control " type="text" name="first_name" value="{{ request.user.first_name }}" />
    
                <label>Last Name:</label>
                <input class="form-control " type="text" name="last_name"  value="{{ request.user.last_name }}"/>
        
                <label>Email:</label>
                <input class="form-control" type="email" name="email" required minlength="3" value="{{ request.user.email }}"/>

                
                <label>City:</label>
                <input class="form-control" type="text" name="city" required minlength="3" value="{{ request.user.profile.city }}"/>
                
                <label>Address:</label>
                <input class="form-control" type="text" name="address" required minlength="3" value="{{ request.user.profile.address }}"/>

                <label>Phone Number:</label>
                <input class="form-control" type="text" name="phone_number" required minlength="3" value="{{ request.user.profile.phone_number }}"/>

                <div class="mb-3">
                    <label>Gender:</label>
                    <select name="gender" id="gender" class="form-select" value="{{ request.user.profile.gender }}">
                        <option value="Male"> Male </option>
                        <option value="Female"> Female </option>
                        <option value="Other"> Other </option>
                    </select>
                </div>
                
                <label>Nationality:</label>
                <input class="form-control" type="text" name="nationality" required minlength="3" value="{{ request.user.profile.nationality }}"/>

                <label>Talk About Your Self:</label>
                <input class="form-control" type="text" name="about" required minlength="3" value="{{ request.user.profile.about }}"/>
        

                <input class="btn btn-secondary mt-3 mb-3" type="submit" value="Update profile" />
            </form>

        </div>

    </div>
</div>
</div>
</section>
</div>

{% endblock %}