LuxeAssist/LuxeAssist/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('request/',include("request.urls")),
    path('accounts/',include("accounts.urls")),
    path('service/',include("services.urls")),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LuxeAssist/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
   path("", views.home_view, name="home_view"),
   path("about/", views.about_view, name="about_view"),
   path("search/", views.search_view, name="search_view"),
   path("contact/", views.contact_view, name="contact_view"),
   path("payment/<requests_id>/", views.payment_view, name="payment_view"),
   path("not/", views.not_found_view, name="not_found_view"),
   path("display/all/contact/",views.display_all_contacts_view, name = "display_all_contacts_view"),
   path('adminn/page/',views.admin_page_view, name="admin_page_view"),
   path("success/payment/",views.success_payment_view, name="success_payment_view" )

]

LuxeAssist/request/urls.py
from django.urls import path
from . import views


app_name = "request"

urlpatterns = [
    path('<service_id>/add/service/', views.add_Request_view, name="add_Request_view"),
    path('user/requests/', views.user_requests_view, name="user_requests_view"),
    path('all/requests/', views.admin_requests_view , name ="admin_requests_view"),
    path('concierge/requests/', views.concierge_requests_view, name="concierge_requests_view"),
    path('details/request/<requsets_id>/', views.request_details_view, name= "request_details_view"),
    path('cancel/request/<requset_id>/', views.cancel_request_view, name="cancel_request_view"),
    path('update/request/<requests_id>/', views.update_price_view, name="update_price_view"),
    path('update/status/<requests_id>/', views.add_status_view, name="add_status_view"),
    path('new/request/<requset_id>/', views.new_requestConcierge_view, name="new_requestConcierge_view"),
    path('delete/request/admin/<requset_id>/',views.delete_request_admin_view, name="delete_request_admin_view"),
    path('request/payment/', views.cheke_isPayment_view, name="cheke_isPayment_view"),
    path('request/unpayment/',views.cheke_unPayment_view, name="cheke_unPayment_view"),
    path('request/user/payment/', views.chekeUser_isPayment_view, name="chekeUser_isPayment_view"),
    path('request/user/unpayment/',views.chekeUser_unPayment_view, name="chekeUser_unPayment_view")
    
]

LuxeAssist/services/urls.py
from django.urls import path
from . import views


app_name = "services"

urlpatterns = [
    path('add/type/', views.add_typeService_view , name="add_typeService_view"),
    path('type/details/<typeService_id>/',views.details_typeService_view, name="details_typeService_view"),
    path('update/type/<typeService_id>/',views.update_typeService_view, name="update_typeService_view"),
    path('delete/<typeService_id>/', views.delete_services_views,name="delete_services_views"),
    path('add/',views.add_service_view , name="add_service_view"),
    path('details/<service_id>/', views.details_service_view, name="details_service_view"),
    path('update/<service_id>/', views.update_service_view, name="update_service_view"),
    path('concierge/delete/<service_id>/',views.delete_servicesConcierge_views, name="delete_servicesConcierge_views"),
    path('all/services/provider/', views.all_servicesProvider_view , name="all_servicesProvider_view"),
    path('activate/user/<user_id>/',views.activate_conceirge_viwe, name = "activate_conceirge_viwe"),
    path('deactivate/user/<user_id>/',views.deactivate_conceirge_viwe, name = "deactivate_conceirge_viwe"),
    path('all/services/admin/', views.all_services_admin_view , name="all_services_admin_view"),
    path('delete/services/admin/<service_id>/', views.delete_services_admin_views , name="delete_services_admin_views"),
    path('all/service/concierge/', views.conceirge_services_view, name = "conceirge_services_view" ),
    path('all/serviceType/admin/',views.all_serviceType_admin_viwe,name="all_serviceType_admin_viwe")

]

LuxeAssist/request/models.py
from django.db import models
from django.contrib.auth.models import User
from services.models import Service

class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    status_type = models.TextChoices("Status", ["Pending", "Approve", "Reject", "Cancle"])
    note = models.TextField()
    date = models.DateTimeField()
    status = models.CharField(max_length = 1024, choices = status_type.choices, default = "pending")
    request_price = models.PositiveIntegerField()

class RequestComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    requests= models.ForeignKey(Request, on_delete=models.CASCADE)
    comment = models.TextField()

LuxeAssist/services/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here


class TypeService(models.Model):
    image=models.ImageField(upload_to="image/", default="image/default_TypeService.jpeg")
    title=models.CharField(max_length=256,default="")
    description=models.TextField(default="")




class Service(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    type_service=models.ForeignKey(TypeService,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="image/", default="image/defaultService.jpg")
    title=models.CharField(max_length=256,default="")
    description=models.TextField(default="")
    initial_price=models.PositiveIntegerField(default=0)



class Review(models.Model):
    services=models.ForeignKey(Service, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    rating= models.IntegerField(default=0)
    comment=models.TextField(default="")
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user}"

LuxeAssist/request/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Request 
from services.models import Service
from .models import RequestComment 
from main.models import Payment




def add_Request_view(request:HttpRequest, service_id):

    if not request.user.is_authenticated:
        return render(request, "main/user_not_found.html", status=401)

    service = Service.objects.get(id = service_id)  
    if request.method == "POST":
        newRequest = Request(user = request.user, service = service, note = request.POST["note"], date = request.POST["date"], request_price = request.POST["request_price"])
        newRequest.save()
        return redirect("request:request_details_view", newRequest.id)
        

def user_requests_view(request: HttpRequest):

        if not request.user.is_authenticated :
           return render(request,"main/user_not_found.html", status=401)
    # try:
        requests = Request.objects.filter(user= request.user)
        
        if "status" in request.GET :
            requests=Request.objects.filter(status=request.GET["status"])
            print(request.GET['status'])

        for index, r in enumerate(requests):
            requests[index].has_payment =  Payment.objects.filter(requests=r).exists()


        return render(request, 'request/user_requests_view.html', {"requests" : requests})
    # except Exception as e:

        # return render(request, "main/user_not_found.html")
    

def concierge_requests_view(request: HttpRequest): 
   # try:
    services=Service.objects.filter(user=request.user)
    requests = Request.objects.filter(service__in=services).order_by("-date")


    if "status" in request.GET :
        requests =Request.objects.filter(service__in=services,status=request.GET["status"])
        print(request.GET['status'])

    for index, r in enumerate(requests):
         requests[index].has_payment =  Payment.objects.filter(requests=r).exists()

    return render(request, 'request/concierge_requests_view.html', {"requests" : requests})





def cheke_isPayment_view(request: HttpRequest):

    requests = Request.objects.filter(payment__requests__service__user=request.user) #only payed payments
    for index, r in enumerate(requests):
        requests[index].has_payment =  Payment.objects.filter(requests=r).exists()
   
    return render(request, 'request/cheke_payment.html', {"requests" : requests})


def cheke_unPayment_view(request: HttpRequest):
   
    requests = Request.objects.filter(service__user=request.user).exclude(payment__requests__service__user=request.user) #only not payed payments
    for index, r in enumerate(requests):
        requests[index].has_payment =  Payment.objects.filter(requests=r).exists()

    
    return render(request, 'request/cheke_unPayment.html', {"requests" : requests})
def chekeUser_isPayment_view(request: HttpRequest):
    
    
    requests = Request.objects.filter(payment__user=request.user) #only payed payments
    for index, r in enumerate(requests):
        requests[index].has_payment =  Payment.objects.filter(requests=r).exists()
   
    return render(request, 'request/cheke_payment.html', {"requests" : requests})


def chekeUser_unPayment_view(request: HttpRequest):
   
    
    requests = Request.objects.filter(user=request.user).exclude(payment__user=request.user)

    
    return render(request, 'request/cheke_unPayment.html', {"requests" : requests})

    

def admin_requests_view(request: HttpRequest):

    if not request.user.is_superuser :
       return render(request,"main/user_not_found.html", status=401)
    try: 
      requests = Request.objects.order_by('-date')
     
     
      return render(request ,"request/admin_requests_view.html" , {"requests" : requests})
    except Exception as e:
      return render(request, "main/user_not_found.html")
   

def request_details_view(request: HttpRequest,requsets_id):
    requests = Request.objects.get(id =requsets_id)

    try:
       
        if request.method == "POST":
            new_Request = RequestComment(user = request.user, requests = requests, comment = request.POST["comment"])
            new_Request.save()
        requestComment=RequestComment.objects.filter(requests = requests)
       
    except Exception as e:
        return redirect("main:home_view")
        
    return render(request ,"request/request_details_view.html", {"requests":requests , "requestComment": requestComment})

     

def cancel_request_view(request: HttpRequest, requset_id):
    if request.user.is_superuser and request.user.is_staff :
       return render(request,"main/user_not_found.html", status=401)
    
    try:
        requests = Request.objects.get(id = requset_id)
        requests.status = "Cancle"
        requests.save()
        return redirect("main:home_view")
        
    except  Exception as e:

        return render(request, "main/user_not_found.html")

def update_price_view(request:HttpRequest, requests_id):

    requests = Request.objects.get(id = requests_id) 

    if request.user.is_superuser and request.user.is_staff :
        return render(request,"main/user_not_found.html", status=401)
     
    if request.method == "POST":
        requests.request_price = request.POST["request_price"]
        requests.save()
        return redirect("request:request_details_view", requsets_id = requests.id)


def add_status_view(request: HttpRequest, requests_id):
    if not request.user.is_authenticated and not request.user.groups.exists :
       return render(request,"main/user_not_found.html", status=401)

    requests = Request.objects.get(id = requests_id)

    if request.method == "POST":
        requests.status = request.POST["status"]
        requests.save()
        return redirect("request:request_details_view",requsets_id = requests.id )
    
def new_requestConcierge_view(request: HttpRequest , requset_id):
    try:
        requests = Request.objects.get(id = requset_id) 

        return render (request, "request/new_requestConcierge_view.html", {"requests": requests})
    except Exception as e:

        return render(request, "main/user_not_found.html")

def delete_request_admin_view(request: HttpRequest, requset_id):

    if not request.user.is_superuser :
        return render(request,"main/user_not_found.html", status=401)
    try:
        requsets=Request.objects.get(id=requset_id)
        requsets.delete()
        return redirect("request:admin_requests_view")
    except  Exception as e:

        return render(request, "main/user_not_found.html") 


def requests_status_viwe(request:HttpRequest,item):
    
    requests_status= Request.objects.filter(status=item)
   
    
    return render(request, "request/concierge_requests_view.html", {"requestsStatus":requests_status})

LuxeAssist/request/templates/request/admin_requests_view.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} All Requests  {% endblock %}
{% block content  %}

   
      
        <div class="container p-3">
            <h1>All Orders</h1>
            {% if requests.count == 0 %}
             <div class="alert alert-info">No order yet.</div>
            {% endif %}
             
        </div>
        <div class="row">
            {% for request in requests %}
            <div class="col-4 p-4 ">
               <div class="card-body gap-2 p-4 border border-1 rounded-2 " style="background-color: #dfdddc5b;">
                     
                <h4> Title service <a href="{% url 'services:details_service_view' request.service.id %}" >{{request.service.title}}</a></h4>
                 
                <h6>Consierge:{{request.service.user.first_name}} {{services.user.last_name}}</h6>
                  
                 <h6>Category:<a href="{% url 'services:details_typeService_view' request.service.type_service.id %}">{{request.service.type_service.title}}</a></h6> 
                  <h4>By user: {{request.user.first_name}} {{request.user.last_name}}</h4>
                  <h4>Note: {{request.note}}</h4>
                  <div class="d-flex flex-row gap-2">
                    <span style="color: rgba(255, 0, 0, 0.34);" class="material-symbols-outlined">
                        payments
                        </span> 
                        <h4>{{request.request_price}} Riyal</h4>
                    </div>
                    <div class="d-flex flex-row g-2">
                        <span style="color: rgba(255, 0, 0, 0.396);" class="material-symbols-outlined">
                            calendar_month
                            </span>
                         <h6>{{request.date }}</h6>
                    </div>
                  
                  <h4> Status :{{request.status}}</h4>
                  <a href="{% url 'request:delete_request_admin_view' request.id %}" class="btn btn-primary">Delete</a>
                </div>    
            </div> 
            {% endfor %}
        </div>
     
        
   


    

{% endblock %}

LuxeAssist/request/templates/request/cheke_payment.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} All Requests  {% endblock %}
{% block content  %}


<div class="row p-5">
    <h1>All Order</h1>
    {% if requests.count == 0 %}
     <div class="alert alert-info">No order yet.</div>
    {% endif %}
     
</div>
    
<div class="row p-3">
    {% for request in requests %}
    <div class="col-4">
 
        <div class="p-2 mt-3" style="background-color: #dfdddc30; border: 10px; border-radius: 20px;">
                <h4>Service <a href="{% url 'services:details_service_view' request.service.id %}" >{{request.service.title}}</a></h4>
                <h6> Your order details:<a href="{% url 'request:request_details_view' request.id %}" >here</a> </h6>
                <h6>Category:<a href="{% url 'services:details_typeService_view' request.service.type_service.id %}">{{request.service.type_service.title}}</a></h6> 
                <h6>{{request.service.description}}</h6>
                <h6> by user: {{request.user.first_name}} {{request.user.last_name}}</h6>
                <h6>note:{{request.note}}</h6>
                <h6>Price by user:{{request.request_price}}</h6>
                <h6>status:{{request.status}}</h6>
                <h6>{{request.date}}</h6>
                {% if request.status == "Approve" %}
                    <h4>Payed : {% if request.has_payment  %} <div class="bg-success p-2 text-white">Payed</div> {% else %} <div class="bg-danger p-2 text-white">Not Payed</div> {% endif %}</h4>
                {% endif %}
            </div>
            

    </div>   
          {% endfor %}   

</div> 
   
      


{% endblock %}

LuxeAssist/request/templates/request/cheke_unPayment.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} All Requests  {% endblock %}
{% block content  %}


<div class="row p-5">
    <h1>All Order</h1>
    {% if requests.count == 0 %}
     <div class="alert alert-info">No order yet.</div>
    {% endif %}
     
</div>
    
<div class="row p-3">
    {% for request in requests %}
    <div class="col-4">
 
        <div class="p-2 mt-3" style="background-color: #dfdddc30; border: 10px; border-radius: 20px;">
                <h4>Service <a href="{% url 'services:details_service_view' request.service.id %}" >{{request.service.title}}</a></h4>
                <h6> Your order details:<a href="{% url 'request:request_details_view' request.id %}" >here</a> </h6>
                <h6>Category:<a href="{% url 'services:details_typeService_view' request.service.type_service.id %}">{{request.service.type_service.title}}</a></h6> 
                <h6>{{request.service.description}}</h6>
                <h6> by user: {{request.user.first_name}} {{request.user.last_name}}</h6>
                <h6>note:{{request.note}}</h6>
                <h6>Price by user:{{request.request_price}}</h6>
                <h6>status:{{request.status}}</h6>
                <h6>{{request.date}}</h6>
                {% if request.status == "Approve" %}
                    <h4>Payed : {% if request.has_payment  %} <div class="bg-success p-2 text-white">Payed</div> {% else %} <div class="bg-danger p-2 text-white">Not Payed</div> {% endif %}</h4>
                {% endif %}
            </div>
            

    </div>   
          {% endfor %}   

</div> 


{% endblock %}

LuxeAssist/request/templates/request/concierge_requests_view.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} All Requests  {% endblock %}
{% block content  %}

   
      
        <div class="row p-4">
            <h1>All Order</h1>
            {% if requests.count == 0 %}
             <div class="alert alert-info">No order yet.</div>
            {% endif %}
             
        </div>


        <div class="dropdown mb-3 d-flex justify-content-between p-3 ">
          <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </button>
          <ul class="dropdown-menu ">
            <li><a class="dropdown-item" href="{% url 'request:concierge_requests_view' %}">All</a></li>
            <li><a class="dropdown-item" href="{% url 'request:concierge_requests_view' %}?status=Approve">Approve</a></li>
            <li><a class="dropdown-item" href="{% url 'request:concierge_requests_view' %}?status=pending">Pending</a></li>
            <li><a class="dropdown-item" href="{% url 'request:concierge_requests_view' %}?status=Reject">Reject</a></li>
            <li><a class="dropdown-item" href="{% url 'request:concierge_requests_view' %}?status=Cancle">Cancle</a></li>
            <li><a class="dropdown-item" href="{% url 'request:cheke_isPayment_view' %}">Paid orders</a></li>
            <li><a class="dropdown-item" href="{% url 'request:cheke_unPayment_view' %}">Unpaid orders</a></li>
          </ul>
         
        </div>

      
    <div class="row p-3">
        {% for request in requests %}
        <div class="col-4">
     
            <div class="p-2 mt-3" style="background-color: #dfdddc30; border: 10px; border-radius: 20px;">
                    <h4>Service <a href="{% url 'services:details_service_view' request.service.id %}" >{{request.service.title}}</a></h4>
                    <h6> Your order details:<a href="{% url 'request:request_details_view' request.id %}" >here</a> </h6>
                    <h6>Category:<a href="{% url 'services:details_typeService_view' request.service.type_service.id %}">{{request.service.type_service.title}}</a></h6> 
                    <h6>{{request.service.description}}</h6>
                    <h6> by user: {{request.user.first_name}} {{request.user.last_name}}</h6>
                    <h6>note:{{request.note}}</h6>
                    <div class="d-flex flex-row gap-2">
                        <span style="color: rgba(255, 0, 0, 0.342);" class="material-symbols-outlined">
                            payments
                            </span> 
                        <h6>by user:{{request.request_price}} Riyal</h6>
                        </div>
                   
                    <h6>status:{{request.status}}</h6>
                    <div class="d-flex flex-row g-2">
                        <span style="color: rgba(255, 0, 0, 0.253);" class="material-symbols-outlined">
                            calendar_month
                            </span>
                         <h6>{{request.date }}</h6>
                    </div>
                    
                    {% if request.status == "Approve" %}
                        <h4>Payed : {% if request.has_payment  %} <div class="bg-success p-2 text-white">Payed</div> {% else %} <div class="bg-danger p-2 text-white">Not Payed</div> {% endif %}</h4>
                    {% endif %}
                </div>
                
    
        </div>   
              {% endfor %}   

    </div> 


{% endblock %}

LuxeAssist/request/templates/request/new_requestConcierge_view.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} All Requests  {% endblock %}
{% block content  %}

   
<h1>All Requests</h1>
<div class="container">

    <div class="row mt-5">
        <div class="col-6">

            
            
            
            <h4>Service :<a href="{% url 'services:details_service_view' requests.service.id %}" >{{requests.service.title}}</a></h4>
            <h4> Your order details:<a href="{% url 'request:request_details_view' requests.id %}" >here</a> </h4>
            <h3>{{requests.date}}</h3>
            <h3>{{requests.request_price}} </h3>
            <h3>{{requests.note}} </h3>  
                
           

        </div>
    </div>
</div>

{% endblock %}

LuxeAssist/request/templates/request/request_details_view.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} detail  {% endblock %}
{% block content  %}

<div class = "container p-5 ">
<div class="row" >
    <div class="mt-3 p-3" style="background-color: rgba(255, 228, 196, 0.395);" >
            <h6>service {{requests.service.title}}</h6> 
            <h6>{{requests.note}}</h6>
            <div class="d-flex flex-row gap-2">
            <span style="color: rgba(255, 0, 0, 0.625);" class="material-symbols-outlined">
                payments
                </span> 
            <h6>{{requests.request_price}} Riyal</h6>
            </div>
            <div class="d-flex flex-row g-2">
                <span style="color: rgba(255, 0, 0, 0.605);" class="material-symbols-outlined">
                    calendar_month
                    </span>
                <h6>{{requests.date}}</h6>
            </div>
        
    </div>
</div>
</div> 
    {% if perms.services.add_service %}

    <div class = "row p-3">
        <div class="col-2">
            
            <form class="d-flex flex-column gap-1"action="{% url 'request:add_status_view' requests.id %}" method="POST">
                {% csrf_token %}
               
                <input TYPE="submit" Name="status" Value="Approve">
                {% if requests.status == "pending"%}
                <input TYPE="submit" Name="status" Value="Reject">
                {% endif %}
                
        
                    
            </form>
        </div>
        
    {% else %}
        <div class = "row p-4">

            <div class = "col-4">
                {% if requests.status == "pending" %}
                <a class="btn btn-dark mb-3 "  data-bs-toggle="modal" data-bs-target="#priceModal">Update Price</a><br>
                {% endif %}
            </div>
            <div class = "col-4">
                {% if requests.status == "pending" %}
                <a class="btn btn-primary" href="{% url 'request:cancel_request_view' requests.id %}">Cancel</a>
                {% endif %}
            </div>

            <div class = "col-2">
                {% if requests.status == "Approve" %}
                <a class="btn btn-primary" href="{% url 'main:payment_view' requests.id %}">Payment</a>
                {% endif %}
            </div>
            
        </div>

        <div class="modal fade" id="priceModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Update Price</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                Do you want to update Price? {{ service.title }} 

                <form action="{% url 'request:update_price_view' requests.id %}" method="POST" >
                    {% csrf_token %}
                    <label class =" mt-2">New Price:</label>
                    <input class="form-control" name="request_price" type="text" required />
                        <input type="submit" value="Update Price" class="btn btn-dark mt-2"/>
                </form>
                </div>
                
                <div class="modal-footer">
                   
                    
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                   
                
                </div>
            </div>
            </div>
        </div>
            
        </div>
    {% endif %}

    <hr>
    <section class="p-3 ">
        <div class="row">
            <h2>Comments</h2>
            <div class="col-4">
                {% for comment in requestComment %}
            
                <h4 id="name">{{comment.user.username}}</h4>
                <div class="p-3" style="  width: 100%; border-radius: 20px; background-color: rgba(255, 228, 196, 0.395);">
                    <p>{{comment.comment}}</p>
                </div>
                {% endfor %}
  
            </div>
        </div>
      
    </section>
   
  
      <div class="row add_rev p-3">
        <div class="col-6 ">
            <h5> Add Comment</h5>
            <form action="{% url 'request:request_details_view' requests.id %}"method="post">
                {% csrf_token %}>
            
            <label>Comment</label>
            <input class="form-control mb-4" type="text" name="comment"/>
            {% if request.user.is_authenticated %}
            <button  class="btn btn-primary mp-4" type="submit"> send </button> 
            {% else %}
            <button  class="btn btn-primary mp-4" type="submit" disabled> send </button>
            
            {%endif%}

            </form>
            
    
    
        </div>
    </div>

 


{% endblock %}

LuxeAssist/request/templates/request/user_requests_view.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} All Requests  {% endblock %}
{% block content  %}

        <div class="row p-4 ">
            <h4 style="color:white; font-size: 50px;">All Order</h4>
            {% if requests.count == 0 %}
             <div class="alert alert-info">No order yet.</div>
            {% endif %}
             
        </div>
        <div class="dropdown mb-3 d-flex justify-content-between p-3 ">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </button>
            <ul class="dropdown-menu ">
              <li><a class="dropdown-item" href="{% url 'request:user_requests_view' %}">All</a></li>
              <li><a class="dropdown-item" href="{% url 'request:user_requests_view' %}?status=Approve">Approve</a></li>
              <li><a class="dropdown-item" href="{% url 'request:user_requests_view' %}?status=pending">Pending</a></li>
              <li><a class="dropdown-item" href="{% url 'request:user_requests_view' %}?status=Reject">Reject</a></li>
              <li><a class="dropdown-item" href="{% url 'request:user_requests_view' %}?status=Cancle">Cancle</a></li>
              <li><a class="dropdown-item" href="{% url 'request:chekeUser_isPayment_view' %}">Paid orders</a></li>
              <li><a class="dropdown-item" href="{% url 'request:chekeUser_unPayment_view' %}">Unpaid orders</a></li>
            </ul>
           
          </div>
            
        <section class="containert">
           
            <div class="row p-3">
                {% for request in requests %}
                <div class="col-4">
                    
                    
                    <hr>
                        <div class="p-3" style="background-color: #ffffff7a;">
                        <h6> {{request.user.first_name}} {{request.user.last_name}}</h6>
                        <h6 style="font-size: 13px;" class="text-muted">Consierge:{{request.service.user.first_name}} {{services.user.last_name}}</h6>
                        <h6> Service:<a href="{% url 'services:details_service_view' request.service.id%}" >{{request.service.title}}</a> </h6>
                        <h6 style="font-size: 13px;" class="text-muted">Category:<a href="{% url 'services:details_typeService_view' request.service.type_service.id %}">{{request.service.type_service.title}}</a></h6> 
                        <h6> Your order details:<a href="{% url 'request:request_details_view' request.id %}" >here</a> </h6>
                        <h5> Your note  {{request.note}}</h5>
                        <div class="d-flex flex-row g-2">
                            <span style="color: rgba(255, 0, 0, 0.605);" class="material-symbols-outlined">
                                calendar_month
                                </span>
                             <h6>{{request.date }}</h6>
                        </div>
                        <h6>status: {{request.status}}</h6>
                        {% if request.status == "Approve" %}
                        <h4>Payed : {% if request.has_payment  %} <div class="bg-success p-2 text-white">Payed</div> {% else %} <div class="bg-danger p-2 text-white">Not Payed</div> {% endif %}</h4>
                        {% endif %}
                    </div>

                    
                </div>
                {% endfor %}
            </div>
        </section>
           
             
              
    
            
     
       
   


    

{% endblock %}