LuxeAssist/LuxeAssist/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('request/',include("request.urls")),
    path('accounts/',include("accounts.urls")),
    path('service/',include("services.urls")),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LuxeAssist/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_page_view, name="register_page_view"),
    path("login/", views.login_page_view, name="login_page_view"),
    path("logout/", views.logout_page_view, name="logout_page_view"),
    path("profile/<user_id>/", views.user_profile_page_view, name="user_profile_page_view"),
    path("update/", views.update_profile_page_view, name="update_profile_page_view"),
]

LuxeAssist/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
   path("", views.home_view, name="home_view"),
   path("about/", views.about_view, name="about_view"),
   path("search/", views.search_view, name="search_view"),
   path("contact/", views.contact_view, name="contact_view"),
   path("payment/<requests_id>/", views.payment_view, name="payment_view"),
   path("not/", views.not_found_view, name="not_found_view"),
   path("display/all/contact/",views.display_all_contacts_view, name = "display_all_contacts_view"),
   path('adminn/page/',views.admin_page_view, name="admin_page_view"),
   path("success/payment/",views.success_payment_view, name="success_payment_view" )

]

LuxeAssist/request/urls.py
from django.urls import path
from . import views


app_name = "request"

urlpatterns = [
    path('<service_id>/add/service/', views.add_Request_view, name="add_Request_view"),
    path('user/requests/', views.user_requests_view, name="user_requests_view"),
    path('all/requests/', views.admin_requests_view , name ="admin_requests_view"),
    path('concierge/requests/', views.concierge_requests_view, name="concierge_requests_view"),
    path('details/request/<requsets_id>/', views.request_details_view, name= "request_details_view"),
    path('cancel/request/<requset_id>/', views.cancel_request_view, name="cancel_request_view"),
    path('update/request/<requests_id>/', views.update_price_view, name="update_price_view"),
    path('update/status/<requests_id>/', views.add_status_view, name="add_status_view"),
    path('new/request/<requset_id>/', views.new_requestConcierge_view, name="new_requestConcierge_view"),
    path('delete/request/admin/<requset_id>/',views.delete_request_admin_view, name="delete_request_admin_view"),
    path('request/payment/', views.cheke_isPayment_view, name="cheke_isPayment_view"),
    path('request/unpayment/',views.cheke_unPayment_view, name="cheke_unPayment_view"),
    path('request/user/payment/', views.chekeUser_isPayment_view, name="chekeUser_isPayment_view"),
    path('request/user/unpayment/',views.chekeUser_unPayment_view, name="chekeUser_unPayment_view")
    
]

LuxeAssist/services/urls.py
from django.urls import path
from . import views


app_name = "services"

urlpatterns = [
    path('add/type/', views.add_typeService_view , name="add_typeService_view"),
    path('type/details/<typeService_id>/',views.details_typeService_view, name="details_typeService_view"),
    path('update/type/<typeService_id>/',views.update_typeService_view, name="update_typeService_view"),
    path('delete/<typeService_id>/', views.delete_services_views,name="delete_services_views"),
    path('add/',views.add_service_view , name="add_service_view"),
    path('details/<service_id>/', views.details_service_view, name="details_service_view"),
    path('update/<service_id>/', views.update_service_view, name="update_service_view"),
    path('concierge/delete/<service_id>/',views.delete_servicesConcierge_views, name="delete_servicesConcierge_views"),
    path('all/services/provider/', views.all_servicesProvider_view , name="all_servicesProvider_view"),
    path('activate/user/<user_id>/',views.activate_conceirge_viwe, name = "activate_conceirge_viwe"),
    path('deactivate/user/<user_id>/',views.deactivate_conceirge_viwe, name = "deactivate_conceirge_viwe"),
    path('all/services/admin/', views.all_services_admin_view , name="all_services_admin_view"),
    path('delete/services/admin/<service_id>/', views.delete_services_admin_views , name="delete_services_admin_views"),
    path('all/service/concierge/', views.conceirge_services_view, name = "conceirge_services_view" ),
    path('all/serviceType/admin/',views.all_serviceType_admin_viwe,name="all_serviceType_admin_viwe")

]

LuxeAssist/main/models.py
from django.db import models
from django.contrib.auth.models import User
from request.models import  Request
# Create your models here.


class Payment(models.Model):
   categories= models.TextChoices("categories", ["Bank Card" ,"pay made "])


   user=models.ForeignKey(User, on_delete=models.CASCADE)
   requests=models.ForeignKey(Request, on_delete=models.CASCADE)
   method_card= models.CharField(max_length=70, choices=categories.choices,default="Cultural")
   full_name= models.CharField(max_length=2048)
   number_card= models.PositiveIntegerField()
   expiration_date =models.DateField()
   cvv=models.PositiveIntegerField()
   
  
   def __str__(self):
     
     return f"{self.full_name}" 
   

class Contact(models.Model):
      
  categories= models.TextChoices("categories", ["Suggestion" ,"Complaint"])
      
  user=models.ForeignKey(User, on_delete=models.CASCADE)
  type=models.CharField(max_length=70, choices=categories.choices,default="Cultural")
  content=models.TextField()

      
  def __str__(self):
        
    return f"{self.type}"

LuxeAssist/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from.models import Payment , Contact
from request.models import Request
from services.models import Service
from services.models import TypeService
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail




# Create your views here.
def home_view(request: HttpRequest):
    

    typeServices=TypeService.objects.all()

    return render(request, "main/home.html" , {"typeServices":typeServices})



def about_view(request: HttpRequest):

    return render(request, "main/about.html")



def contact_view(request: HttpRequest):

   
    if request.method=="POST":
        #try:

            contact = Contact(user=request.user, type=request.POST["type"], content=request.POST["content"])
            contact.save()

            return redirect("main:contact_view")
        #except:
            return render(request, "main/user_not_found.html")
    
    user_contact= Contact.objects.filter(user= request.user)
    
    return render(request, "main/contact.html", {"categories": Contact.categories ,"user_contact" : user_contact}) 



def payment_view(request: HttpRequest ,requests_id):
    msg=None
    if not request.user.is_authenticated and request.user.groups.exists and request.user.is_superuser and request.user.is_staff :
        return render(request,"main/user_not_found.html", status=401)
 
    requests=Request.objects.get(id=requests_id)
    
    if request.method=="POST":
        try:
            new_payment=Payment( requests=requests ,user=request.user, method_card=request.POST["method_card"], full_name=request.POST["full_name"], number_card=request.POST["number_card"],expiration_date=request.POST["expiration_date"], cvv = request.POST["cvv"])
            new_payment.save()
            subject = 'welcome to LuxeAssist world'

            message = f'Hi {request.user.first_name} {request.user.last_name}, Thank you for trusting us, your payment was completed successfully.\n Your order details:\nTitle:{requests.service.title}\nDescription:{requests.service.description}\nDate:{requests.date}\nPrice:{requests.request_price}\nSee you soon, dont forget to visit us again.'

            from_email = settings.EMAIL_HOST_USER


            recipient_list = [request.user.email]
            send_mail( subject=subject, message=message, from_email=from_email, recipient_list=recipient_list )
            return redirect("main:success_payment_view")
        except Exception as e:
            msg = f"An error occured, please fill in all fields and try again . {e}"

    return render(request, "main/payment.html",{"requests": requests , "categories": Payment.categories ,"msg":msg}) 


def not_found_view(request: HttpRequest):

   return render(request, "main/user_not_found.html")



def display_all_contacts_view(request:HttpRequest):

    if  not request.user.is_superuser and not request.user.is_staff  :
            return render(request,"main/user_not_found.html", status=401)

    contacts = Contact.objects.all()
    return render(request, "main/display_all_contacts.html", {"contacts": contacts})
  


def search_view(request: HttpRequest):
    
    if "search" in request.GET:

        keyword = request.GET["search"]
        services = Service.objects.filter(title__contains=keyword)
        print("dddd")
        
    else:
        services = Service.objects.all()

    print(services)
    return render(request, "main/searsh.html", {"services" : services })



def admin_page_view(request: HttpRequest):
     
    if not request.user.is_superuser :
        return render(request,"main/user_not_found.html", status=401)

    return render(request,"main/admin_page.html")


def success_payment_view(request: HttpRequest):
    
    return render(request, "main/success_payment.html")

LuxeAssist/main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %} About {% endblock %}

{% block content %}


<div class ="container p-5">
    <h1 style="color: rgb(67, 40, 9);">About Us</h1>
    <p style="font-size: 20px;">Welcome to LuxeAssist, a distinguished provider of premier personal and professional services, strategically positioned to alleviate the challenges associated with time management, effort, and lifestyle organization. Our commitment is unwavering - to enhance the quality of life for our esteemed clients through meticulous attention to their needs, offering unparalleled precision and efficiency.</p>

    <h5 style="color:rgb(77, 45, 9);">Our Distinctive Approach: A Strategic Investment in Time</h5>

    <p style="font-size: 20px;">
        LuxeAssist distinguishes itself as an unparalleled service, endowing our members with the invaluable resource of time. Beyond the conventional, we unlock gates to comfort and luxury, offering an expansive suite of personal and professional services catering to life's fundamental necessities, desires, and exigencies. LuxeAssist is not merely about today; it's a commitment to curating a complete luxury lifestyle that transcends the present.</p>


        <p style="font-size: 20px;">LuxeAssist stands firmly behind the Vision 2030 exhibition, aligning seamlessly with the endeavor to provide visitors with an immersive and distinctive experience, underscored by our exceptional services.</p>

</div>



{% endblock %}
  

LuxeAssist/main/templates/main/admin_page.html
{% extends 'main/base.html' %}
{% block title %} admin page {% endblock %}
{% block content %}


<section class="container-admin p-5 mb-5 ">
    <div class="row d-flex justify-content-center">
        <br>
        <br>
        <br>
    <h4 style="color: white;"> Admin </h4>
        <div class="col-6 mb-5" style="margin-bottom: -20rem;">
            <ul class="list-group">
                <a href="{% url 'services:all_servicesProvider_view' %}"><li class="list-group-item btn btn-dark" style="background-color:rgba(204, 182, 163, 0.473)">All Consierge </li></a>
                <a href="{% url 'services:all_services_admin_view' %}"><li class="list-group-item btn btn-dark"  style="background-color:rgba(204, 182, 163, 0.473)">All concierge services  </li></a>
                <a href="{% url 'request:admin_requests_view' %}"><li class="list-group-item btn btn-dark" style="background-color:rgba(204, 182, 163, 0.473)">All user order  </li></a>
                <a href="{% url 'main:display_all_contacts_view' %}"><li class="list-group-item btn btn-dark" style="background-color:rgba(204, 182, 163, 0.473)">All Contacts  </li></a>
                <a href="{% url 'services:add_typeService_view' %}"><li class="list-group-item btn btn-dark" style="background-color:rgba(204, 182, 163, 0.473)"> Add Service categories</li></a>   
                <a href="{% url 'services:all_serviceType_admin_viwe' %}"><li class="list-group-item btn btn-dark" style="background-color:rgba(204, 182, 163, 0.473)"> All Service categories</li></a>  
            </ul>
        </div>
    </div>
</section>
{% endblock%}

LuxeAssist/main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/style.css" />
   </head>
  <body>
     <!-- Navbar  -->
     <nav class="navbar fixed-top navbar-expand-lg navbar-dark p-mb-5 " style="background-color: #745e43;">
      <div class="container">
        <a class="navbar-brand" href="#">LuxeAssist</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <div class="mx-auto"></div>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'main:home_view' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'main:about_view' %}">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'main:contact_view' %}">Contact</a>
            </li>
            {%endif%}
            <li class="nav-item">
              {% if request.user.is_superuser %}
                  <a class="nav-link text-white" href="{% url 'main:admin_page_view'%}">Admin</a>
              {%endif%}   
            </li>
        
            <li class="nav-item dropdown">
            {% if user.is_authenticated and user.groups.exists %}
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Consierge 
              </a> 
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'services:conceirge_services_view'%}">All services</a></li>
                <li><a class="dropdown-item" href="{% url 'request:concierge_requests_view' %}">All Order</a></li>
                <li><a class="dropdown-item" href="{% url 'services:add_service_view' %}">Add Service</a></li>
              </ul>
            {%endif%}
            </li>
          </ul>
          
          
          {% if request.user.is_authenticated %}
          <div>
            <img class="rounded-circle avatar p-2" width="50px" src="{{ request.user.profile.avatar.url }}" />
          </div>
          <li class="nav-item dropdown d-flex p-2 justify-content-center">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Welcome {{ request.user.username }}
            </a> 
            <ul class="dropdown-menu">
          
              <li><a class="dropdown-item" href="{% url 'accounts:user_profile_page_view' user.id %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:update_profile_page_view' %}">Update Profile</a></li>
              {% if user.is_authenticated and not user.groups.exists %}
                 <li><a class="dropdown-item" href="{% url 'request:user_requests_view' %}">All Order</a></li>
              {% endif %}
              
              <li><a class="dropdown-item" href="{%url 'accounts:logout_page_view' %}">LogOut</a></li>
        {% else %}
              <li><a class="dropdown-item" href="{% url 'accounts:login_page_view' %}">Sign Up</a></li>
        {% endif%}
              
            </ul>
          </li>
     
        </div>
        
      </div>
    </nav>
    <div class="wrapper mt-5">
    {% block content %}

    {% endblock %} 
    </div>
<hr>
    <div class="row p-3">
      <div class="col-12 col-md">
        <img class="mb-2" src="\static\images\logo.png" alt="" width="200" height="60">
        <small class="d-block mb-3 text-body-secondary">© 2017–2023</small>
      </div>
      <div class="col-6 col-md">
        <h5>Connect us</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="mailto:info@realeastate.com">Email</a></li>
          <li class="mb-1"><a  class="link-secondary text-decoration-none" href="tel:+966562736534">Phone</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
        <!-- <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-box">
                           
                         
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quam repellendus sunt praesentium aspernatur iure molestias.</p>
                        <h3>We Accect</h3>
                        <div class="card-area">
                                <i class="fa fa-cc-visa"></i>
                                <i class="fa fa-credit-card"></i>
                                <i class="fa fa-cc-mastercard"></i>
                                <i class="fa fa-cc-paypal"></i>
                        </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-box">
                            <h2>Hosting</h2>
                        <ul>
                            <li><a href="#">Web Hosting</a></li>
                            <li><a href="#">Cloud Hosting</a></li>
                            <li><a href="#">CMS Hosting</a></li>
                            <li><a href="#">WordPress Hosting</a></li>
                            <li><a href="#">Email Hosting</a></li>
                            <li><a href="#">VPS Hosting</a></li>
                        </ul>
                        </div>                    
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-box">
                            <h2>Domain</h2>
                        <ul>
                            <li><a href="#">Web Domain</a></li>
                            <li><a href="#">Cloud Domain</a></li>
                            <li><a href="#">CMS Domain</a></li>
                            <li><a href="#">WordPress Domain</a></li>
                            <li><a href="#">Email Domain</a></li>
                            <li><a href="#">VPS Domain</a></li>
                        </ul>
                        </div>                    
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single-box">
                            <h2>Newsletter</h2>
                            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur doloremque earum similique fugiat nobis. Facere?</p>
                             <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Enter your Email ..." aria-describedby="basic-addon2">
                                <span class="input-group-text" id="basic-addon2"><i class="fa fa-long-arrow-right"></i></span>
                            </div>
                            <h2>Follow us on</h2>
                            <p class="socials">
                                <i class="fa fa-facebook"></i>
                                <i class="fa fa-dribbble"></i>
                                <i class="fa fa-pinterest"></i>
                                <i class="fa fa-twitter"></i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer> -->
    
    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/js/bootstrap.min.js">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    

 
  </body>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="/static/js/responses.js"></script>
  <script src="/static/js/chat.js"></script>
  

</html>

LuxeAssist/main/templates/main/contact.html
{% extends 'main/base.html' %}
{% block title %} Contact {% endblock %}
{% block content %}

<section class="container p-4">

    <h1>Contact</h1>

    <div class="card-Contact">
    <form action="{% url 'main:contact_view' %}" method="POST"  enctype="multipart/form-data">
        {% csrf_token %}  
       
        <label >Content:</label>
        <textarea  class="form-control" name="content"></textarea>
         
        {% for key, value in categories.choices  %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="type" id="{{key}}" value="{{value}}">
                <label class="form-check-label" for="{{key}}">
                {{value}}
              </label>
            </div>
        {% endfor %}

        {% if request.user.is_authenticated %}
           <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#content" >send</button>
        {%else%}
           <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#content" disabled >send</button>
        {%endif%}

        <div class="modal" tabindex="1" id="content">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title"> Contact Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p style="color: black;">We have received your contact. We will respond to you within 24 hours. Follow your email</p>
                  </div>
              <div class="modal-footer">
                <button class="btn btn-primary mt-2" type="submit" data-bs-dismiss="modal" >ok</button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div> 
 
  </div> 
</div>



<!-- modal -->
<div class="modal" tabindex="1" id="content">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"> Contact Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p style="color: black;">We have received your contact. We will respond to you within 24 hours. Follow your email</p>
          </div>
      <div class="modal-footer">
        <button class="btn btn-primary mt-2" type="submit" data-bs-dismiss="modal" >Send</button>
      </div>
    </div>
  </div>
</div>
</section>




<div class="row ">
  {% if user_contact.count == 0 %}
  <div class="alert alert-info">No contact yet.</div>
  {% endif %}
  
</div>

<section class="container">
  <h4>All contact</h4>
  
    <div class="row">
        <div class="col-5">
            {% for contact in user_contact %}
            <hr>
                <h4> {{contact.user.first_name}} {{contact.user.last_name}}</h4>
                <h4> {{contact.type}}</h4>
                <h4>{{contact.content}}</h4>
               
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

LuxeAssist/main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %} home {% endblock %}
{% block content %}

<div class="homepage">

    <div class="row">
        <div class="title col">
         <h1>LuxeAssist</h1> 
        <p style="font-size: 20px;">LuxeAssist distinguishes itself as an unparalleled service, endowing our members with the invaluable resource of time. Beyond the conventional, we unlock gates to comfort and luxury, offering an expansive suite of personal and professional services catering to life's fundamental necessities, desires, and exigencies. LuxeAssist is not merely about today; it's a commitment to curating a complete luxury lifestyle that transcends the present.</p>
         <h5>WHAT ARE YOU LOOKING FOR? </h5>
          <div class="input-group rounded w-50">
             <form role="search" action="{% url 'main:search_view' %}" method="GET">  
                 <input name="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
             </form>
         </div>
         
    </div>
</div>  

</div>  
     
<br>

<div class="container row d-flex justify-content-center align-items-center" style="margin: 0px auto;">
 
    <h4 class="text-1">Discover our services</h4>
    <br><br>
  
    {% for service in typeServices %}
    <section id="card1 " class="card_service col-3 ms-1 ">
        <img class="image h-40 w-40" src="{{service.image.url}}" alt="Card image cap">
        <div class="card__content">
           <a style="color: white;" href="{% url 'services:details_typeService_view' service.id %}" ><p class="card__title">{{service.title}}</p></a>
          <p class="card__description">{{service.description}}.</p>
        </div>
      </section>
    {% endfor %}
</div>
     
   

{% endblock %}

LuxeAssist/main/templates/main/not_authorized.html
{% extends 'main/base.html' %}
{% block title %} Not Authorized {% endblock %}
{% block content %}

<section class="container">

    <div class="row">

        <div class="col">
            <h2>Unautorized </h2>
            <p>Please contact us on <a href="mailto:admin@gmail.com">admin@gmail.com</a>.</p>
        </div>

    </div>

</section>
{% endblock %}

LuxeAssist/main/templates/main/payment.html
{% extends 'main/base.html' %}
{% block title %} Payment {% endblock %}
{% block content %}

<section class="container">

    <h1>Add New Payment</h1>

    <div class="row">
        {% if msg %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
        {% endif %}
    <div class="col-6">
    <form action="{% url 'main:payment_view' requests.id %}" method="POST">
        {% csrf_token %}  
        <label>Full name:</label>
        <input class="form-control" type="text" name="full_name" placeholder="Full Name" required minlength="4" />

        {% for key , value in categories.choices %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="method_card" id="{{key}}" value="{{value}}">
                        <label class="form-check-label" for="{{key}}">
                            {{value}}
                        </label>
                    </div>
                {% endfor %}
        
        <label>Number:</label>
        <input class="form-control" type="text" name="number_card" placeholder="Name" required minlength="4" />
         
        <label >Expiration Date:</label>
        <input  class="form-control" name="expiration_date" type="date" />

        <label>CVV:</label>
        <input class="form-control" type="number" name="cvv" placeholder="cvv" required minlength="2" />
        
        <input class="btn btn-primary mt-2" type="submit" value=" Payment" />
 
     </form>
   </div> 
 
</div> 
</section>

{% endblock %}

LuxeAssist/main/templates/main/searsh.html
{% extends 'main/base.html' %}

{% block title %} All  {% endblock %}

{% block content %}

<section class="container pt-4">

    <div class="d-flex justify-content-between">
    
    <h1>Search results for service`{{ request.GET.search }}` ({{ services.count }})</h1>
    
        <div class="container row">
            
        {%for services in services %}
        <div class="col-4 g-2">
      
      
            <div class="d-flex flex-row gap-3">
                <div class="card-body gap-3 p-3 rounded-2 " style="background-color: #dfdddc5b; width: 100%; box-shadow: 0 3px 8px #000000;">
                    
                    
                  <img src="{{services.image.url}}" height="200px" width="100%">
                    <div class="d-flex gap-1">
                    <img class="avatar mt-3" src="{{ user.profile.avatar.url }}" width="60px" style="border-radius:50%" class="rounded-circle" />
                    </div>
                    <h6 class="card-title"> Consierge {{services.user.first_name}} {{services.user.last_name}}</h6>
                    <br>
                    <a href="{% url 'services:details_service_view' services.id %}" ><h2>{{services.title}}</h2></a>
                    <h6>{{services.description}}</h6>
                    <h6>Price {{services.initial_price}}</h6>
                </div>
            
              </div>
              
            </div>
    {% endfor %}
    </div>
    </div>
</section>
{% endblock %}

LuxeAssist/main/templates/main/success_payment.html
{% extends 'main/base.html' %}


{% block title %} User Not found  {% endblock %}
{% block content  %}

<div class ="wrapper pages-content">
    <div class = "row content d-flex flex-column align-items-center ">
 
            <h1 class= "mt-5 mb-5">success payment</h1>
            <a class="btn btn-primary" href="{% url 'request:user_requests_view' %}">Back to orderes</a>
            
     </div>
</div>



{% endblock %}

LuxeAssist/main/templates/main/user_not_found.html
{% extends 'main/base.html' %}


{% block title %} User Not found  {% endblock %}
{% block content  %}

<div class ="wrapper pages-content">
    <div class = "row content d-flex flex-column align-items-center ">
 
            <h1 class= "mt-5 mb-5">Sorry! The page you want does not exist{{message}}</h1>
            
     </div>
</div>



{% endblock %}