LuxeAssist/LuxeAssist/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('request/',include("request.urls")),
    path('accounts/',include("accounts.urls")),
    path('service/',include("services.urls")),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LuxeAssist/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register_page_view, name="register_page_view"),
    path("login/", views.login_page_view, name="login_page_view"),
    path("logout/", views.logout_page_view, name="logout_page_view"),
    path("profile/<user_id>/", views.user_profile_page_view, name="user_profile_page_view"),
    path("update/", views.update_profile_page_view, name="update_profile_page_view"),
]

LuxeAssist/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
   path("", views.home_view, name="home_view"),
   path("about/", views.about_view, name="about_view"),
   path("search/", views.search_view, name="search_view"),
   path("contact/", views.contact_view, name="contact_view"),
   path("payment/<requests_id>/", views.payment_view, name="payment_view"),
   path("not/", views.not_found_view, name="not_found_view"),
   path("display/all/contact/",views.display_all_contacts_view, name = "display_all_contacts_view"),
   path('adminn/page/',views.admin_page_view, name="admin_page_view"),
   path("success/payment/",views.success_payment_view, name="success_payment_view" )

]

LuxeAssist/request/urls.py
from django.urls import path
from . import views


app_name = "request"

urlpatterns = [
    path('<service_id>/add/service/', views.add_Request_view, name="add_Request_view"),
    path('user/requests/', views.user_requests_view, name="user_requests_view"),
    path('all/requests/', views.admin_requests_view , name ="admin_requests_view"),
    path('concierge/requests/', views.concierge_requests_view, name="concierge_requests_view"),
    path('details/request/<requsets_id>/', views.request_details_view, name= "request_details_view"),
    path('cancel/request/<requset_id>/', views.cancel_request_view, name="cancel_request_view"),
    path('update/request/<requests_id>/', views.update_price_view, name="update_price_view"),
    path('update/status/<requests_id>/', views.add_status_view, name="add_status_view"),
    path('new/request/<requset_id>/', views.new_requestConcierge_view, name="new_requestConcierge_view"),
    path('delete/request/admin/<requset_id>/',views.delete_request_admin_view, name="delete_request_admin_view"),
    path('request/payment/', views.cheke_isPayment_view, name="cheke_isPayment_view"),
    path('request/unpayment/',views.cheke_unPayment_view, name="cheke_unPayment_view"),
    path('request/user/payment/', views.chekeUser_isPayment_view, name="chekeUser_isPayment_view"),
    path('request/user/unpayment/',views.chekeUser_unPayment_view, name="chekeUser_unPayment_view")
    
]

LuxeAssist/services/urls.py
from django.urls import path
from . import views


app_name = "services"

urlpatterns = [
    path('add/type/', views.add_typeService_view , name="add_typeService_view"),
    path('type/details/<typeService_id>/',views.details_typeService_view, name="details_typeService_view"),
    path('update/type/<typeService_id>/',views.update_typeService_view, name="update_typeService_view"),
    path('delete/<typeService_id>/', views.delete_services_views,name="delete_services_views"),
    path('add/',views.add_service_view , name="add_service_view"),
    path('details/<service_id>/', views.details_service_view, name="details_service_view"),
    path('update/<service_id>/', views.update_service_view, name="update_service_view"),
    path('concierge/delete/<service_id>/',views.delete_servicesConcierge_views, name="delete_servicesConcierge_views"),
    path('all/services/provider/', views.all_servicesProvider_view , name="all_servicesProvider_view"),
    path('activate/user/<user_id>/',views.activate_conceirge_viwe, name = "activate_conceirge_viwe"),
    path('deactivate/user/<user_id>/',views.deactivate_conceirge_viwe, name = "deactivate_conceirge_viwe"),
    path('all/services/admin/', views.all_services_admin_view , name="all_services_admin_view"),
    path('delete/services/admin/<service_id>/', views.delete_services_admin_views , name="delete_services_admin_views"),
    path('all/service/concierge/', views.conceirge_services_view, name = "conceirge_services_view" ),
    path('all/serviceType/admin/',views.all_serviceType_admin_viwe,name="all_serviceType_admin_viwe")

]

LuxeAssist/services/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here


class TypeService(models.Model):
    image=models.ImageField(upload_to="image/", default="image/default_TypeService.jpeg")
    title=models.CharField(max_length=256,default="")
    description=models.TextField(default="")




class Service(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    type_service=models.ForeignKey(TypeService,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="image/", default="image/defaultService.jpg")
    title=models.CharField(max_length=256,default="")
    description=models.TextField(default="")
    initial_price=models.PositiveIntegerField(default=0)



class Review(models.Model):
    services=models.ForeignKey(Service, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    rating= models.IntegerField(default=0)
    comment=models.TextField(default="")
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user}"

LuxeAssist/services/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User,Group
from .models import TypeService , Service, Review
from accounts.models import Profile
# Create your views here.

### Type Service View

def add_typeService_view(request:HttpRequest):
    msg=None
    if  not request.user.is_superuser and not request.user.is_staff :
            return render(request,"main/user_not_found.html", status=401)
    
    if request.method=="POST":
        try:
            new_service=TypeService(title=request.POST["title"],description=request.POST["description"], image=request.FILES["image"])
            new_service.save()
            return redirect("main:home_view")
        except Exception as e:
            msg = f"An error occured, please fill in all fields and try again . {e}"
        
    return render(request,"services/add_typeService.html" ,{"msg":msg})


def details_typeService_view(request:HttpRequest, typeService_id):
    msg=None
    
    try:
        typeServices=TypeService.objects.get(id=typeService_id)
        services=Service.objects.filter(type_service=typeServices)

    except Exception as e:
        msg=f"Sorry, something went wrong. Try again later {e}"

    return render(request , "services/details_typeService.html",{"typeService":typeServices , "services":services ,"msg":msg})

def all_serviceType_admin_viwe(request:HttpRequest):

    typeServices=TypeService.objects.all()

    return render(request , "services/all_serviceType_admin.html",{"typeService":typeServices})

def update_typeService_view(request:HttpRequest,typeService_id):
    msg=None
    if  not request.user.is_superuser and not request.user.is_staff :
        return render(request,"main/user_not_found.html", status=401)
    
    typeService= TypeService.objects.get(id=typeService_id)

    if request.method=="POST":
        try:
        
            typeService.title=request.POST["title"]
            typeService.description=request.POST["description"]
            if "image" in request.FILES:
                typeService.image=request.FILES["image"]
            typeService.save()

            return redirect("services:all_serviceType_admin_viwe") 
        except Exception as e:
            msg = f"An error occured, please fill in all fields and try again . {e}"
        

        
    return render(request,"services/update_typeServices.html",{"typeService":typeService ,"msg":msg})


def delete_services_views(request:HttpRequest, typeService_id):

    if  not request.user.is_superuser and not request.user.is_staff :
        return render(request,"main/user_not_found.html", status=401)

    typeService= TypeService.objects.get(id = typeService_id)
    typeService.delete()
    return redirect("services:all_serviceType_admin_viwe")


### Service View

def add_service_view(request:HttpRequest):
    msg=None
    service_types = TypeService.objects.all()

    if not request.user.has_perm("services.add_service"): #not work with admin 
        return render(request,"main/user_not_found.html", status=401) 

    if request.method== "POST":
        try:
            typeservices=TypeService.objects.get(id=request.POST["type"])
            new_service=Service(user=request.user, type_service=typeservices , title=request.POST["title"],description=request.POST["description"], image=request.FILES["image"] , initial_price=request.POST["initial_price"])
            new_service.save()

            return redirect("services:details_typeService_view", typeService_id=typeservices.id)
        except Exception as e:
            msg=f"An error occured, please fill in all fields and try again . {e}"

    
    return render(request , "services/add_service.html", { "service_types" : service_types ,"msg": msg})

def details_service_view(request:HttpRequest, service_id):
    msg=None
    try:
        service=Service.objects.get(id=service_id)
        if request.method=="POST":
            try:
                reviews=Review(services=service,user=request.user,rating=request.POST["rating"],comment=request.POST["comment"])
                reviews.save()
            except Exception as e:
                msg=f"Sorry, something went wrong. Try again later {e}"

        reviews=Review.objects.filter(services=service)

        return render(request , "services/details_services.html",{"service":service , "reviews":reviews ,"msg":msg})
    except Exception as e:
        return redirect("main:not_found_view")


def update_service_view(request:HttpRequest, service_id):
    msg=None
    service=Service.objects.get(id=service_id)

    if  not request.user.has_perm("services.change_service"):#not work with admin
        return render(request,"main/user_not_found.html", status=401)   
    if request.method=="POST":

        try:

            service.title=request.POST["title"]
            service.description=request.POST["description"] 
            if "image" in request.FILES:
                service.image=request.FILES["image"]
            service.initial_price=request.POST["initial_price"]
            service.save()

            return redirect("services:conceirge_services_view")
        except Exception as e:
            msg=f"An error occured, please fill in all fields and try again . {e}"
        
    
    return render(request,"services/update_service.html",{"service": service,"msg":msg })

def delete_servicesConcierge_views(request:HttpRequest, service_id):
    if  not request.user.has_perm("services.delete_service"):#not work with admin
        return render(request,"main/user_not_found.html", status=401) 
    
    service=Service.objects.get(id=service_id)
    service.delete()
    return redirect("services:conceirge_services_view")


def all_servicesProvider_view (request:HttpRequest):

    msg=None
    if  not request.user.is_superuser and not request.user.is_staff:
            return render(request,"main/user_not_found.html", status=401)
    try:
        coceirge_users = User.objects.filter(groups__name="conceirge")
    except Exception as e:
        msg=f"Sorry, something went wrong. Try again later {e}"


    return render(request,"services/all_services_rovider.html", {"coceirge_users": coceirge_users,"msg":msg})


def activate_conceirge_viwe(request:HttpRequest,user_id):
    if  not request.user.is_superuser :
        return render(request,"main/user_not_found.html", status=401)
    
    user =  User.objects.get(id = user_id)
    user.is_active = True
    user.save()
    
    return redirect("services:all_servicesProvider_view")


def deactivate_conceirge_viwe(request:HttpRequest,user_id):
    if  not request.user.is_superuser :
        return render(request,"main/user_not_found.html", status=401)
    
    user =  User.objects.get(id = user_id)
    user.is_active = False
    user.save()
    return redirect("services:all_servicesProvider_view")



def all_services_admin_view(request:HttpRequest):
    msg=None
    if  not request.user.is_superuser and not request.user.is_staff  :
            return render(request,"main/user_not_found.html", status=401)
    try:
        all_services = Service.objects.all()
    except Exception as e:
        msg=f"Sorry, something went wrong. Try again later {e}"

    return render (request,"services/all_services_admin.html",{"all_services":all_services,"msg":msg})


def delete_services_admin_views(request:HttpRequest, service_id):

    if  not request.user.is_superuser :
            return render(request,"main/user_not_found.html", status=401)

    service=Service.objects.get(id=service_id)
    service.delete()
    return redirect("services:all_services_admin_view")




def conceirge_services_view(request:HttpRequest):
    msg=None
    if not request.user.has_perm("services.add_service"): #not work with admin 
        return render(request,"main/user_not_found.html", status=401)
    try:
        service = Service.objects.filter(user = request.user)
    except Exception as e:
        msg=f"Sorry, something went wrong. Try again later {e}"



    return render(request , 'services/conceirge_services.html', {"service":service ,"msg":msg})

LuxeAssist/services/templates/services/add_service.html
{% extends 'main/base.html' %}


{% block title %} All Services {% endblock %}


{% block content %}

<div class="container">

    <div class="row mt-5">
        {% if msg %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
        {% endif %}
        <div class="col-5">
            <form action="{% url 'services:add_service_view' %}" method="POST" enctype="multipart/form-data" class="d-flex flex-column gap-2">
                {% csrf_token %}

                <label>Title</label>
                <input class="form-control" name="title" type="text" required minlength="4"/>
                
                <label>Description</label>
                <input class="form-control" name="description" type="text" required minlength="10"/>

                <label>Image</label>
                <input class="form-control" name="image" type="file"  accept="image/*"/>

                <label>Initial price</label>
                <input class="form-control" name="initial_price" type="text" required />
                
                <label>Service categories</label>
                <select class="form-select" name="type">
                    {% for type in service_types %}
                        <option value="{{ type.id }}">{{type.title}}</option>
                    {% endfor %}
                </select>

                <input class="btn btn-primary" type="submit" value="Add Service" />
            </form>

        </div>
    </div>
</div>

{% endblock %}

LuxeAssist/services/templates/services/add_typeService.html
{% extends 'main/base.html' %}


{% block title %} Add Type Services {% endblock %}


{% block content %}
<div class="container">
    <h5>Welcome</h5>
    <div class="row">
        {% if msg %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
        {% endif %}
        <div class="col-5">
            <form  action="{% url 'services:add_typeService_view' %}" method="POST" enctype="multipart/form-data" class="d-flex flex-column gap-2">
                {% csrf_token %}

                <label>Image</label>
                <input class="form-control" name="image" type="file"  accept="image/*"/>

                <label>Title Service:</label>
                <input class="form-control" name="title" type="text" minlength="4" required />

                <label>Description:</label>
                <input class="form-control" name="description" type="text" minlength="10" required />


                <input class="btn btn-primary" type="submit" value="Add Service" />

            </form>
        </div>
    </div>
</div>




{% endblock %}

LuxeAssist/services/templates/services/all_serviceType_admin.html
{% extends 'main/base.html' %}


{% block title %} All Services Admin Page {% endblock %}


{% block content %}
<div>
  {% if msg %}
  <div class="alert alert-danger" role="alert">
      {{ msg }}
  </div>
  {% endif %}

  <div class="row p-4" style="margin-top:100px;">
    <h2 style="align-content: center;"> All Sservice Category</h2>
  {% for services in typeService %}
 <div class="col-7 g-3">
  
  <div class="p-4 d-flex justify-content-center flex-column align-items-center" style="background-color: #dfdddc5b; border-radius: 20px;">
      
    <img src="{{services.image.url}}" height="600px" width="100%">
      <h5 class="p-2" >{{services.title}}</h5>
      <h6 style="color: black;"> {{services.description}}</h6>

    
    </div>

  
</div>
<div class="button-edit dropdown p-2">
    <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Edit  
    </button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="{% url 'services:delete_services_views' services.id %}">Delete Service categories</a></li>
      <li><a class="dropdown-item" href="{% url 'services:update_typeService_view' services.id %}">Update Service categories</a></li>
      
    </ul>
  </div>

  {% endfor %}
    </div>
{% endblock %}

LuxeAssist/services/templates/services/all_services_admin.html
{% extends 'main/base.html' %}


{% block title %} All Services Admin Page {% endblock %}


{% block content %}
<div>
  {% if msg %}
  <div class="alert alert-danger" role="alert">
      {{ msg }}
  </div>
  {% endif %}

  <div class="row p-4" style="margin-top:100px;">
    <h2 style="align-content: center;"> All Sservice consierge</h2>
  {% for services in all_services %}
 <div class="col-4 g-3 ">
  <div class="d-flex flex-row gap-2 col-4">
  <div class="card-body border border-1 rounded-2 p-4 " style="background-color: #dfdddc5b;">
      
    <img src="{{services.image.url}}" height="200px" width="360px">
      <div class="d-flex gap-1">
      <img class="avatar mt-4" src="{{ services.user.profile.avatar.url }}" width="50px" style="border-radius:50%" class="rounded-circle" />
      <h5 class="card-title  mt-5" style="color: rgb(87, 3, 3);"> Consierge:  {{services.user.first_name}} {{services.user.last_name}}</h5>
      </div>
      <br>
      <h5 class="title-1">Servise title: <a href="{% url 'services:details_service_view' services.id %}" >{{services.title}}</a></h5>
      <h5 >Category: <a href="{% url 'services:details_typeService_view' services.type_service.id %}">{{services.type_service.title}}</a></h5>
      <h6 style="color: black;"> {{services.description}}</h6>
      <h6> Price {{services.initial_price}}</h6>
      <h6>{{services.initial_price}}</h6>
      <a href="{% url 'services:delete_services_admin_views' services.id %}" class="btn btn-primary">Delete</a>
    </div>
  </div>
</div>

  {% endfor %}
    </div>
{% endblock %}

LuxeAssist/services/templates/services/all_services_rovider.html
{% extends 'main/base.html' %}


{% block title %} All Services Provider {% endblock %}


{% block content %}
<div class="wrapper ">
  {% if msg %}
  <div class="alert alert-danger " role="alert">
      {{ msg }}
  </div>
  {% endif %}

<div class="row p-4 justify-content-center" style="margin-top:100px; ">
{% for user in coceirge_users %}
<div class=" ard_service col-3 ms-1">
 <div class="card " style="width: 20rem; height:25rem ;  margin: 40px auto; background-color: #ffffff7a; " >
   <div class="card-body" >
      {% if user.is_active %} <h3>Active</h3> {% else %} <h3>Not Active</h3> {% endif %}
     <img class="avatar mt-3" src="{{ user.profile.avatar.url }}" width="50px" style="border-radius:50%" class="rounded-circle" />
     <h5 class="card-title">Name:{{user.first_name}} {{user.last_name}}</h5>
     <a href="mailto:{{ user.email }}"><h5 class="card-title">Email:{{user.email}}</h5></a>
     <a href="tel:{{user.profile.phone_number}}"><h5 class="card-title">Phone Number: {{user.profile.phone_number}}</h5></a>
     <a href="{% url 'services:activate_conceirge_viwe' user.id %}" class="btn btn-primary">Activate</a>
     <a href="{% url 'services:deactivate_conceirge_viwe' user.id %}" class="btn btn-primary">Deactivate</a>
   </div>
 </div>
</div>
 {% endfor %}
</div>
</div>
{% endblock %}

LuxeAssist/services/templates/services/conceirge_services.html
{% extends 'main/base.html' %}


{% block title %} All Services {% endblock %}


{% block content %}

<div style="margin: 0px auto; " class="p-5">
    <h2>All Service </h2>
    {% if msg %}
    <div class="alert alert-danger" role="alert">
        {{ msg }}
    </div>
    {% endif %}
    <div class="row">
        {% for service in service %}
        <div class="col-4 g-2 p-4" style="height: 100%;">
            <div>
                <div class="p-3" style="background-color: #dfdddc5b; width: 100%; box-shadow: 0 3px 8px #000000;height: 100%;">
                    
                    
                  <img src="{{service.image.url}}" height="200px" width="100%">
                    <a href="{% url 'services:details_service_view' service.id %}" ><h2>{{service.title}}</h2></a>
                    <h6>Category:<a href="{% url 'services:details_typeService_view' service.type_service.id %}">{{service.type_service.title}}</a></h6> 
                    <h6>{{service.description}}</h6>
                    <div class="d-flex flex-row gap-2">
                      <span style="color: rgba(255, 0, 0, 0.625);" class="material-symbols-outlined">
                          payments
                          </span> 
                      <h6>{{service.initial_price}} Riyal</h6>
                      </div>
                      <div class="d-flex flex-row justify-content-between">
                        <a class="btn btn-primary" href="{% url 'services:update_service_view' service.id %}">Update </a>
                        <a class="btn btn-primary" href="{% url 'services:delete_servicesConcierge_views' service.id %}">Delete</a>
                      </div>
                </div>
            
              </div>

              
              
            </div>
        




        {% endfor %}

      


</div>

{% endblock %}

LuxeAssist/services/templates/services/details_services.html
{% extends 'main/base.html' %}


{% block title %}  Services {% endblock %}


{% block content %}

<div class="start1">
  <img src="{{service.image.url}}" style="z-index: -1; width: 100%; height: 80vh;" />
  <div class="d-flex flex-column justify-content-center align-items-center" style="margin-top: -15vh; color: white; ">
    <div class="card-body gap-2 p-3 rounded-2 col-8" style="background-color: #4b3519e8;" >
      <h2 class="contant">Service {{service.title}}</h2>
      <h5>category: {{service.type_service.title}}</h5>
    <div class="d-flex flex-row gap-1">
      <h4> <h5 style="color: rgb(250, 250, 250);">Consierge </h5>{{service.user.first_name}} {{service.user.last_name}}</h4>
    </div>  
    <h5>{{service.description}}</h5>
    <div class="d-flex flex-row gap-2">
      <span style="color: rgba(255, 0, 0, 0.625);" class="material-symbols-outlined">
          payments
          </span> 
      <h6>{{service.initial_price}} Riyal</h6>
      </div>
    
    
    <a class="btn btn-dark mb-3 "  data-bs-toggle="modal" data-bs-target="#orderModal">Order</a>
   </div>
</div>
<div class="container">
  <div class="row">
  {% if msg %}
    <div class="alert alert-danger" role="alert">
        {{ msg }}
    </div>
  {% endif %}
  

  </div>
  </div>




    
    <div class="modal fade" id="orderModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Order</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Do you want to request this service? {{service.title}}

            <form action="{% url 'request:add_Request_view' service.id %}" method="POST" >
                {% csrf_token %}
                    <label class =" mt-2">order time:</label>
                    <input class="form-control" name="date" type="datetime-local" />

                    <label class =" mt-2">note:</label>
                    <textarea class="form-control" name="note"></textarea>

                    <label>price</label>
                    <input class="form-control" name="request_price" type="text" required />

                    <input type="submit" value="Order" class="btn btn-dark mt-2"/>
            </form>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
           
            </div>
        </div>
        </div>
    </div>
</div>
<div style="background-color:#f0ebd6;">
  <section class="p-3 mt-3">
    <div clss="row ">
        <h2>Reviews</h2>
        <div class="col-12 d-flex flex-column gap-2 ">
            {% for review in reviews %}
            <hr>
            <div class="review d-flex flex-column gap-2">
                <h3 id="name">{{review.user.username}}</h3>
                <h5  class="text-muted">{{review.rating}} <span class="material-symbols-outlined">grade</span></h>
                <p style="color: black;">{{review.comment}}</p>
                <h6 class="text-muted" >{{review.created_at}}</h6>
            </div>
            {% endfor %}

        </div>
    </div>
  
</section>

  <hr>

 

    <div class="row add_rev p-3">
      <div class="col-6 ">
          <h5> Add Review</h5>
          <form action="{% url 'services:details_service_view' service.id %}"method="post">
              {% csrf_token %}
          <div class="rate ">
                                <input type="radio" id="star5" name="rating" value="5" />
                                <label for="star5" title="text">5 stars</label>
                                <input type="radio" id="star4" name="rating" value="4" />
                                <label for="star4" title="text">4 stars</label>
                                <input type="radio" id="star3" name="rating" value="3" />
                                <label for="star3" title="text">3 stars</label>
                                <input type="radio" id="star2" name="rating" value="2" />
                                <label for="star2" title="text">2 stars</label>
                                <input type="radio" id="star1" name="rating" value="1" />
                                <label for="star1" title="text">1 star</label>
                            </div>
          

          
          <input class="form-control mb-4" type="text" name="comment" placeholder="comment"/>
          {% if request.user.is_authenticated %}
          <button  class="btn btn-primary mp-4" type="submit"> Add Review </button> 
          {% else %}
          <button  class="btn btn-primary mp-4" type="submit" disabled> Add Review </button>
          
          {%endif%}
          <br>
  
          <a>To post a review please <a href="{% url 'accounts:login_page_view' %}">sign in</a>.
  
          </form>
          
  
  
      </div>
  </div>
</div>




{% endblock %}

LuxeAssist/services/templates/services/details_typeService.html
{% extends 'main/base.html' %}


{% block title %} Add Type Services {% endblock %}


{% block content %}


<div class="start1">
  <img src="{{typeService.image.url}}" width="100%" height="600vh" style="z-index: -1;"/>

  <div class="d-flex flex-column justify-content-center align-items-center" style="margin-top: -15rem; color: white; ">
    <h2 class="contant">{{typeService.title}}</h2>
    <h5 class="contant" style="font-size: 23px; width: 60%;">{{typeService.description}}</h5>
   </div>
</div>

<div class="container p-3 mt-3">
   {% if msg %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
        {% endif %}

    <div class="row " style="margin-top:100px;">
      {% for services in services %}
    <div class="col-4 g-4">
      
      
        <div class="d-flex flex-row gap-3" style="height:100%;">
            <div class="gap-3 p-3 rounded-2 " style="background-color: #dfdddc5b; width: 100%; box-shadow: 0 3px 8px #000000;">
                
                
              <img src="{{services.image.url}}" height="200px" width="100%">
                <div class="d-flex gap-1">
                <img class="avatar mt-3" src="{{ services.user.profile.avatar.url }}" width="60px" style="border-radius:50%" class="rounded-circle" />
                </div>
                <h6 class="card-title"> Consierge {{services.user.first_name}} {{services.user.last_name}}</h6>
                <br>
                <a href="{% url 'services:details_service_view' services.id %}" ><h2>{{services.title}}</h2></a>
                <h6>{{services.description}}</h6>
                <div class="d-flex flex-row gap-2">
                  <span style="color: rgba(255, 0, 0, 0.625);" class="material-symbols-outlined">
                      payments
                      </span> 
                  <h6>lnitial price {{services.initial_price}} Riyal</h6>
                  </div>
              
            </div>
        
          </div>
          
        </div>
    {% endfor %}
    </div>


{% endblock %}

LuxeAssist/services/templates/services/update_service.html
{% extends 'main/base.html' %}


{% block title %} All Type Services {% endblock %}


{% block content %}



<div class="container p-3">
    <h3>Update </h3>
    <br>
    <div class="row">
        {% if msg %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
        {% endif %}
        <div class="col-6">
            <form action="{% url 'services:update_service_view' service.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Title</label>
                <input class="form-control" name="title" type="text" required minlength="4"/>
                
                <label>Description</label>
                <input class="form-control" name="description" type="text" required minlength="10" />

                <label>Image</label>
                <input class="form-control" name="image" type="file"  accept="image/*"/>

                <label>Initial price</label>
                <input class="form-control" name="initial_price" type="text" required />
                

                <input class="btn btn-primary" type="submit" value="Update Service" />
            </form>

        </div>
    </div>
</div>

{% endblock %}